sidebar:
  author: lfyszy
  avatar: https://cdn.luogu.com.cn/upload/usericon/748131.png
  description: 这是一条 DarkFish,喜欢唱跳rap篮球music
  yiyan:
    enable: false
  nav:
    关于: /about/
    归档: /archive/
    分类: /category/    
    标签: /tag/
    友链: /friend/
comment:
  enable: true
  url: https://comment.lfyszy.top